= Personalized PageRank

// tag::introduction[]
As mentioned above, calculating the exact betweenness centrality on large graphs can be very time consuming.
Therefore, you might choose to use an approximation algorithm that will run much quicker, and still provide useful information.
// end::introduction[]

.The following will run the algorithm and stream results:
[source,cypher]
----
include::scripts/pagerank.cypher[tag=ppr-stream-sample-graph]
----

.The following will run the algorithm and write back results:
[source,cypher]
----
include::scripts/pagerank.cypher[tag=ppr-write-ppr-graph]
----

// tag::ppr-stream-graph-result[]
.Results
[opts="header",cols="1,1"]
|===
| Name    | PageRank
| Home    | 3.232
| Product | 1.059
| Links   | 1.059
| About   | 1.059
| Site A  | 0.328
| Site B  | 0.328
| Site C  | 0.328
| Site D  | 0.328
|===
// end::ppr-stream-graph-result[]

// tag::stream-ppr-graph-explanation[]
Alice is still the main broker in the network, and Charles is a minor broker, although their centrality score has reduced as the algorithm only considers relationships at a depth of 1.
The others don’t have any influence, because all the shortest paths between pairs of people go via Alice or Charles.
// end::stream-ppr-graph-explanation[]